import type { Sender, Step } from './types';

const jordan: Sender = {
  name: 'Jordan',
  role: 'Account Manager',
};

export const homepageFlow: Step[] = [
  // ── a. Account upgrade alerts ──────────────────────────────────────
  {
    id: 'msg-1',
    type: 'slack-message',
    sender: jordan,
    content:
      'We need a way to alert the sales team whenever an account upgrades their plan. Can you set something up?',
    action: { label: 'Start ticket' },
    delay: 500,
  },
  {
    id: 'reply-1',
    type: 'reply',
    content:
      "Sure, I'll emit an event on upgrade and wire up a subscriber for sales.",
    sendLabel: 'Send',
    delay: 250,
  },
  {
    id: 'code-1',
    type: 'code-editor',
    filename: 'account-events.ts',
    language: 'typescript',
    lines: [
      "import { registerWorker, TriggerAction } from 'iii-sdk'",
      '',
      'const iii = registerWorker(process.env.III_ENGINE_URL, {',
      "  workerName: 'account-events',",
      '})',
      '',
      "iii.registerFunction('accounts::on-upgrade', async ({ companyId }) => {",
      '  // existing logic...',
      '  iii.trigger({',
      "    function_id: 'publish',",
      "    payload: { topic: 'account.upgraded', data: { companyId } },",
      '    action: TriggerAction.Void(),',
      '  })',
      '})',
      '',
      'iii.registerTrigger({',
      "  type: 'subscribe', function_id: 'sales::notify-team',",
      "  config: { topic: 'account.upgraded' },",
      '})',
    ],
    writeLabel: 'Write',
    doneLabel: 'Deploy',
    delay: 300,
  },
  {
    id: 'status-1',
    type: 'status',
    variant: 'info',
    icon: 'connect',
    headline: 'Event channel live',
    detail: 'Sales team receives real-time upgrade alerts',
    autoAdvance: 1400,
    delay: 200,
  },

  // ── b. AI agent for strategic clients ──────────────────────────────
  {
    id: 'msg-2',
    type: 'slack-message',
    sender: jordan,
    content:
      'Love it. Now we need an AI agent that watches for strategic client upgrades and pulls their full company details for review.',
    action: { label: 'View request' },
    delay: 500,
  },
  {
    id: 'reply-2',
    type: 'reply',
    content:
      'Let me create an agentic worker and subscribe it to the same event.',
    sendLabel: 'Send',
    delay: 250,
  },
  {
    id: 'code-2',
    type: 'code-editor',
    filename: 'strategic_observer.py',
    language: 'python',
    lines: [
      'from iii import register_worker, InitOptions',
      '',
      "iii = register_worker(os.environ['III_ENGINE_URL'], InitOptions(",
      "    worker_name='ai-agent',",
      '))',
      '',
      'async def strategic_observer(event):',
      "    company = iii.trigger({ 'function_id': 'accounts::get-details', 'payload': event })",
      '    # ...analyze with LLM, enrich with company data...',
      "    return { 'analysis': '...' }",
      '',
      "iii.register_function('agents::strategic-observer', strategic_observer)",
      'iii.register_trigger({',
      "    'type': 'subscribe', 'function_id': 'agents::strategic-observer',",
      "    'config': { 'topic': 'account.upgraded' },",
      '})',
    ],
    writeLabel: 'Write',
    doneLabel: 'Deploy',
    delay: 300,
  },
  {
    id: 'status-2',
    type: 'status',
    variant: 'info',
    icon: 'connect',
    headline: 'AI agent observing upgrades',
    detail: 'Strategic clients automatically flagged for review',
    autoAdvance: 1400,
    delay: 200,
  },

  // ── c. Legacy application integration ──────────────────────────────
  {
    id: 'msg-3',
    type: 'slack-message',
    sender: jordan,
    content:
      "OK here's a tough one, could take more than a few days. We need to integrate a legacy application but we can't touch its codebase.",
    action: { label: 'View request' },
    delay: 500,
  },
  {
    id: 'reply-3',
    type: 'reply',
    content:
      "No problem. I'll write a worker for its API endpoints and connect it.",
    sendLabel: 'Send',
    delay: 250,
  },
  {
    id: 'code-3',
    type: 'code-editor',
    filename: 'legacy-proxy.js',
    language: 'javascript',
    lines: [
      "const { registerWorker } = require('iii-sdk')",
      '',
      'const iii = registerWorker(process.env.III_ENGINE_URL, {',
      "  workerName: 'legacy-proxy',",
      '})',
      '',
      'const legacyEndpoints = [',
      "  { path: '/legacy/webhook', id: 'legacy::webhook' },",
      "  { path: '/legacy/orders', id: 'legacy::orders' },",
      ']',
      '',
      "const legacyBaseUrl = process.env.LEGACY_API_URL || 'https://legacy.example.com'",
      '',
      'legacyEndpoints.forEach(({ path, id }) => {',
      '  iii.registerFunction(id, {',
      '    url: `${legacyBaseUrl}${path}`,',
      "    method: 'POST',",
      '  })',
      '})',
    ],
    writeLabel: 'Write',
    doneLabel: 'Deploy',
    delay: 300,
  },
  {
    id: 'status-3',
    type: 'status',
    variant: 'info',
    icon: 'connect',
    headline: 'Legacy system connected',
    detail:
      'Receiving traffic through the hook without touching the original codebase',
    autoAdvance: 1400,
    delay: 200,
  },

  // ── d. Already connected to AI ─────────────────────────────────────
  {
    id: 'msg-4',
    type: 'slack-message',
    sender: jordan,
    content:
      'Great, how soon can you get it connected to the AI agent? I told the client 2 weeks.',
    action: { label: 'View request' },
    delay: 500,
  },
  {
    id: 'reply-4',
    type: 'reply',
    content: 'Already done.',
    sendLabel: 'Send',
    delay: 250,
  },

  // ── e–f. The punchline ─────────────────────────────────────────────
  {
    id: 'msg-5',
    type: 'slack-message',
    sender: jordan,
    content: 'When did you find the time to do that?',
    action: { label: 'Reply' },
    delay: 600,
  },
  {
    id: 'reply-5',
    type: 'reply',
    content: "It's a single system. Everything is connected.",
    sendLabel: 'Send',
    delay: 250,
  },
  {
    id: 'status-4',
    type: 'status',
    variant: 'success',
    icon: 'check',
    headline: 'All services connected',
    detail: 'Every worker shares the same event bus and state',
    autoAdvance: 1600,
    delay: 200,
  },

  // ── g–h. Observability and fix ─────────────────────────────────────
  {
    id: 'msg-6',
    type: 'slack-message',
    sender: jordan,
    content:
      "Excellent work! I've just heard from the client — they're experiencing some intermittent issues with AI evals. How long to investigate?",
    action: { label: 'View request' },
    delay: 500,
  },
  {
    id: 'reply-6',
    type: 'reply',
    content:
      "I've got end-to-end observability and traces, should only take a moment.",
    sendLabel: 'Send',
    delay: 1000,
  },
  {
    id: 'reply-7',
    type: 'reply',
    content:
      'There it is, turns out the prompt was including every company. I set it to only those over $50k ARR.',
    sendLabel: 'Send',
    delay: 250,
  },
  {
    id: 'code-4',
    type: 'code-editor',
    filename: 'strategic-observer-fix.ts',
    language: 'typescript',
    lines: [
      "iii.registerFunction('agents::strategic-observer', async (event) => {",
      '  const company = await iii.trigger({',
      "    function_id: 'accounts::get-details', payload: event,",
      '  })',
      '  return await iii.trigger({',
      "    function_id: 'llm-service::respond',",
      '    payload: {',
      '      // ...',
      '      messages: [{',
      "        role: 'system',",
      "        content: 'Only flag upgrades for follow-up if company ARR > $50k.',",
      "      }, { role: 'user', content: JSON.stringify(company) }],",
      '    },',
      '  })',
      '})',
    ],
    writeLabel: 'Apply fix',
    doneLabel: 'Deploy',
    delay: 300,
  },
  {
    id: 'status-5',
    type: 'status',
    variant: 'success',
    icon: 'observe',
    headline: 'Issue identified and resolved',
    detail: 'Prompt guard added — agent scoped to high-value accounts',
    autoAdvance: 1600,
    delay: 200,
  },
];
