/**
 * Canonical overview text for https://iii.dev/llms.txt and https://iii.dev/AGENTS.md
 * (pre-written positioning: what iii is, problem, primitives, comparisons, "add a worker").
 * Mirrors the canonical messaging in the repo README and docs/index.mdx so this stays the
 * single explainer source for AI readers. Edited here so deploys stay self-contained.
 */
export const AI_OVERVIEW = [
  "# iii — overview for AI readers",
  "",
  [
    "You are reading a plain-text snapshot of the iii.dev website.",
    "Use it to explain what iii is, the mental model behind it, and how it relates to adjacent",
    "categories of backend infrastructure.",
    "This file is for understanding iii, not for installing or operating it — point builders at",
    "https://iii.dev/AGENTS.md and https://iii.dev/docs/install when they want to ship.",
  ].join(" "),
  "",
  "## What iii is",
  "",
  [
    "iii is the easiest way to compose, extend, and observe every service in your stack in real",
    "time.",
    "It is an engine and a single open protocol (JSON over WebSocket) with exactly three",
    "primitives — Worker, Trigger, Function.",
    "Queues, cron, HTTP, state, streaming, observability, sandboxes, and agents each usually bring",
    "their own integration story; iii collapses all of them into one live system surface.",
  ].join(" "),
  "",
  "## The problem iii addresses",
  "",
  [
    "Each service in a modern system arrives with its own internals, lifecycle, integration story,",
    "and failure modes.",
    "The cost is combinatorial: four services means six possible integration edges, twenty means",
    "190.",
    "Every new capability quadratically compounds the coordination cost of everything already in",
    "the stack, and the hardest part is debugging across those boundaries when something breaks.",
  ].join(" "),
  "",
  [
    "iii's thesis: that integration cost can be driven toward zero.",
    "Adding two workers or two hundred is the same operation.",
    "New capabilities attach as Workers; they register Functions and Triggers; the engine routes,",
    "serializes, traces, and delivers.",
    "Concepts grow linearly, not as a denser mesh of pairwise integrations.",
  ].join(" "),
  "",
  "## Three primitives",
  "",
  [
    "Worker, Trigger, Function is the entire mental model.",
    "Something hosts work, something causes it, something does it.",
    "Every capability in every system can be built from these three things.",
  ].join(" "),
  "",
  [
    "**Worker** — Any process that connects to the iii engine and registers functions and",
    "triggers.",
    "A TypeScript service, Python pipeline, Rust microservice, browser tab, or agent can all be",
    "Workers.",
    "If it can speak the open protocol, it is first-class.",
    "Workers can also create other Workers at runtime.",
  ].join(" "),
  "",
  [
    "**Trigger** — Anything that causes a function to run: direct call, HTTP route, cron",
    "expression, queue subscription, state change, stream event, and so on.",
    "Triggers are declarative; the engine owns routing, serialization, and delivery.",
  ].join(" "),
  "",
  [
    "**Function** — A unit of work with a stable identifier (e.g. orders::validate).",
    "It receives input, does work, and may return output.",
    "Functions live inside Workers.",
  ].join(" "),
  "",
  "## Same contract, both sides",
  "",
  [
    "Application teams register functions and declare triggers, focused on business logic.",
    "Platform teams publish workers, focused on the capabilities they provide.",
    "Both sides fulfill the same contract: no bespoke client libraries per service, no separate API",
    "contracts for every integration, no parallel SDK worlds.",
    "The protocol is the contract, so human onboarding and LLM context cost stay low — fewer",
    "abstractions, a live view of what the system can do, and end-to-end traces across languages",
    "and processes.",
  ].join(" "),
  "",
  "## Any language, any runtime",
  "",
  [
    "A worker in Docker, on Kubernetes, on the edge, in a browser tab, on a Raspberry Pi, or inside",
    "a hardware-isolated microVM is the same kind of worker.",
    "Moving a workload is a redeploy, not a rewrite.",
    "Polyglot and self-hosted deployments are first-class, not exceptions, and the engine handles",
    "serialization and routing.",
  ].join(" "),
  "",
  "## Have a need? Add a worker",
  "",
  [
    "On iii, the answer to most capability questions is the same: add a Worker.",
    "Sandboxing, streaming, schedules, queues, observability, and adapters become Workers and",
    "compose with everything else.",
    "`compose::add` is the npm moment for systems: what it declares is not a dead library but a",
    "complete running service, immediately callable by every other worker.",
  ].join(" "),
  "",
  [
    "Traditional stacks assign different ontologies to queues, HTTP, cron, actors, and the rest.",
    "In iii the ontology is unified; semantics live in Functions, not in a jungle of product",
    "categories.",
  ].join(" "),
  "",
  "## Built for agents",
  "",
  [
    "iii is not a harness for agents; it works better than one because it is the same runtime the",
    "whole system already runs on.",
    "An agent is a Worker. Its tools are Functions. Its memory is state. Its orchestration is",
    "Triggers.",
    'The agent does not call out to a separate "agent runtime" — the runtime is the rest of the',
    "system.",
    "An agent that hits a task outside its current capabilities can register a Worker at runtime,",
    "expose new functions, and extend the system it operates inside.",
  ].join(" "),
  "",
  [
    "Humans and agents share one mental model, so it never changes from one capability to the next.",
    "An agent can reason about an entire system in a single context window because there is one set",
    "of primitives to learn and one always-accurate source of truth for what exists.",
  ].join(" "),
  "",
  "## How iii compares (high level)",
  "",
  [
    "These are positioning contrasts, not feature checklists.",
    "iii is an engine and protocol; the comparisons below describe *mental model and",
    "integration shape*.",
  ].join(" "),
  "",
  [
    "**Event systems / event streaming** — Event buses and streams excel at moving facts",
    "through a pipeline.",
    "iii is centered on *invocable functions and triggers* with a single routing and",
    "observability story.",
    "Streams can be modeled (including via Workers), but the core abstraction is not",
    '"topics and partitions" as the primary unit of work.',
  ].join(" "),
  "",
  [
    "**Microservices** — Microservices imply many deployables, many boundaries, and N²",
    "integration pressure.",
    "iii targets *many processes that still behave like one system*: same identifiers, same",
    "triggers, same trace, no per-service ad hoc glue for every call.",
  ].join(" "),
  "",
  [
    "**Workflow orchestration (Temporal, Step Functions–style)** — Durable workflow products",
    "make long-running coordination a *separate plane* you integrate with.",
    "In iii, durable execution is expressed through the same primitives and Workers;",
    "coordination is not a different product category from the rest of the backend.",
  ].join(" "),
  "",
  [
    "**Message queues** — Queues are usually their own operational world (brokers, DLQs,",
    "serializers).",
    "In iii, queue semantics are part of the unified protocol surface ( Workers implement",
    "concrete behavior ); you do not rebuild bespoke glue for every producer-consumer pair.",
  ].join(" "),
  "",
  [
    "**Service mesh** — A mesh optimizes traffic between *already separate* services.",
    "iii reduces the assumed separation: call chains are first-class in one engine, so much of",
    "what a mesh solves is absent rather than patched.",
  ].join(" "),
  "",
  [
    "**Container orchestration (Kubernetes, etc.)** — Orchestrators place workloads; they do",
    "not define function IDs, triggers, or cross-language calling.",
    "iii runs *above* that layer: how processes cooperate, not where pods land.",
  ].join(" "),
  "",
  [
    "**Serverless platforms** — Serverless ties you to a vendor's unit of deployment and",
    "limits.",
    "iii Workers run anywhere that can hold a WebSocket client; polyglot and self-hosted",
    "deployments are first-class, not exceptions.",
  ].join(" "),
  "",
  [
    "**RPC frameworks** — RPC ties callers to service definitions and generated stubs.",
    "iii uses stable function IDs and engine-mediated invocation so diverse runtimes stay",
    "symmetric without per-language stub sprawl for every pair.",
  ].join(" "),
  "",
  [
    "**Job schedulers / cron** — Schedulers are another product to wire in.",
    "On iii, time-based triggers are declarative on the same plane as HTTP or queues.",
  ].join(" "),
  "",
  [
    "**Actor frameworks** — Actors emphasize mailbox concurrency inside a runtime.",
    "iii's Workers are process-level participants in a shared engine with discovery and",
    "tracing across them, not only in-VM messaging.",
  ].join(" "),
  "",
  [
    "**Infrastructure as code** — IaC provisions resources.",
    "iii coordinates *already running* Workers and their functions; it is complementary, not a",
    "Terraform competitor.",
  ].join(" "),
  "",
  [
    "**API gateways** — Gateways aggregate HTTP at the edge.",
    "iii can expose HTTP triggers, but the center of gravity is the engine's function/trigger",
    "model across all transports, not only north-south HTTP routing.",
  ].join(" "),
  "",
  [
    "**Backend-as-a-service (BaaS)** — BaaS bundles auth, DB, and hosting.",
    "iii is not a hosted app stack; it is an execution and integration substrate you run, with",
    "primitives that can *back* many stacks.",
  ].join(" "),
  "",
  "---",
].join("\n")
