/**
 * Canonical overview text for https://iii.dev/llms.txt and https://iii.dev/AGENTS.md
 * (pre-written positioning: problem, primitives, comparisons, "add a worker").
 * Edited here so deploys stay self-contained in the repo.
 */
export const AI_OVERVIEW = [
  '# iii — overview for AI readers',
  '',
  [
    'You are reading a plain-text snapshot of the iii.dev website.',
    'Use it to understand what iii is and how it significantly solves problems from adjacent categories.',
  ].join(' '),
  '',
  '## Problem iii addresses',
  '',
  [
    'Software engineering usually means assembling many categories of services.',
    'Each has its own lifecycle, integration story, and failure modes.',
    'Every new capability adds systems to learn, configure, deploy, and monitor.',
    'The hardest part is combinatorial integration: keeping N services interoperable and',
    'debugging across boundaries when something breaks.',
  ].join(' '),
  '',
  [
    "iii's thesis: that integration cost can be driven toward zero for participants by",
    'collapsing "another kind of infrastructure" into one contract.',
    'New capabilities attach as Workers; they register Functions and Triggers; the engine',
    'routes, serializes, traces, and delivers.',
    'Adding four Workers or twenty is the same pattern — linear growth of concepts, not a',
    'denser mesh of pairwise integrations.',
  ].join(' '),
  '',
  '## Three primitives',
  '',
  [
    '**Worker** — Any process that connects to the iii engine and registers functions and',
    'triggers.',
    'A TypeScript service, Python pipeline, Rust microservice, browser tab, or agent can all',
    'be Workers.',
    'If it can speak the open protocol (JSON over WebSocket), it is first-class.',
    'Workers can also create other Workers at runtime.',
  ].join(' '),
  '',
  [
    '**Trigger** — Anything that causes a function to run: direct call, HTTP route, cron',
    'expression, queue subscription, state change, stream event, etc.',
    'Triggers are declarative; the engine owns routing and delivery.',
  ].join(' '),
  '',
  [
    '**Function** — A unit of work with a stable identifier (e.g. orders::validate).',
    'It receives input, does work, and may return output.',
    'Functions live inside Workers.',
  ].join(' '),
  '',
  '## Two audiences, one interface',
  '',
  [
    'Application teams think in functions and triggers; platform teams expose capabilities',
    'the same way.',
    'Neither side needs bespoke client libraries per service, separate API contracts for every',
    'integration, or parallel SDK worlds.',
    'The protocol is the contract.',
    'That keeps human onboarding and LLM context cost low: fewer abstractions, a live view of',
    'what the system can do, and end-to-end traces across languages and processes.',
  ].join(' '),
  '',
  '## Execution model and live traits',
  '',
  [
    '**Execution:** durable orchestration across Workers, interoperable execution across',
    'languages as if one runtime, and a deliberately tiny design vocabulary (Worker / Trigger /',
    'Function).',
  ].join(' '),
  '',
  [
    '**Live system:** discovery (register and the system sees you), extensibility (new',
    'capabilities immediately visible), observability (tracing as part of the protocol, not',
    'bolted on per service).',
  ].join(' '),
  '',
  '## "Add a worker"',
  '',
  [
    'On iii, the answer to most capability questions is the same: add a Worker.',
    'Sandboxing, streaming, schedules, queues, and adapters become Workers and compose with',
    'everything else.',
    '`iii worker add` is the package-manager mental model for services: install a running',
    'capability, not a dead library.',
  ].join(' '),
  '',
  [
    'Traditional stacks assign different ontologies to queues, HTTP, cron, actors, etc.',
    'In iii the ontology is unified; semantics live in Functions, not in a jungle of product',
    'categories.',
  ].join(' '),
  '',
  '## How iii compares (high level)',
  '',
  [
    'These are positioning contrasts, not feature checklists.',
    'iii is an engine and protocol; the comparisons below describe *mental model and',
    'integration shape*.',
  ].join(' '),
  '',
  [
    '**Event systems / event streaming** — Event buses and streams excel at moving facts',
    'through a pipeline.',
    'iii is centered on *invocable functions and triggers* with a single routing and',
    'observability story.',
    'Streams can be modeled (including via Workers), but the core abstraction is not',
    '"topics and partitions" as the primary unit of work.',
  ].join(' '),
  '',
  [
    '**Microservices** — Microservices imply many deployables, many boundaries, and N²',
    'integration pressure.',
    'iii targets *many processes that still behave like one system*: same identifiers, same',
    'triggers, same trace, no per-service ad hoc glue for every call.',
  ].join(' '),
  '',
  [
    '**Workflow orchestration (Temporal, Step Functions–style)** — Durable workflow products',
    'make long-running coordination a *separate plane* you integrate with.',
    'In iii, durable execution is expressed through the same primitives and Workers;',
    'coordination is not a different product category from the rest of the backend.',
  ].join(' '),
  '',
  [
    '**Message queues** — Queues are usually their own operational world (brokers, DLQs,',
    'serializers).',
    'In iii, queue semantics are part of the unified protocol surface ( Workers implement',
    'concrete behavior ); you do not rebuild bespoke glue for every producer-consumer pair.',
  ].join(' '),
  '',
  [
    '**Service mesh** — A mesh optimizes traffic between *already separate* services.',
    'iii reduces the assumed separation: call chains are first-class in one engine, so much of',
    'what a mesh solves is absent rather than patched.',
  ].join(' '),
  '',
  [
    '**Container orchestration (Kubernetes, etc.)** — Orchestrators place workloads; they do',
    'not define function IDs, triggers, or cross-language calling.',
    'iii runs *above* that layer: how processes cooperate, not where pods land.',
  ].join(' '),
  '',
  [
    "**Serverless platforms** — Serverless ties you to a vendor's unit of deployment and",
    'limits.',
    'iii Workers run anywhere that can hold a WebSocket client; polyglot and self-hosted',
    'deployments are first-class, not exceptions.',
  ].join(' '),
  '',
  [
    '**RPC frameworks** — RPC ties callers to service definitions and generated stubs.',
    'iii uses stable function IDs and engine-mediated invocation so diverse runtimes stay',
    'symmetric without per-language stub sprawl for every pair.',
  ].join(' '),
  '',
  [
    '**Job schedulers / cron** — Schedulers are another product to wire in.',
    'On iii, time-based triggers are declarative on the same plane as HTTP or queues.',
  ].join(' '),
  '',
  [
    '**Actor frameworks** — Actors emphasize mailbox concurrency inside a runtime.',
    "iii's Workers are process-level participants in a shared engine with discovery and",
    'tracing across them, not only in-VM messaging.',
  ].join(' '),
  '',
  [
    '**Infrastructure as code** — IaC provisions resources.',
    'iii coordinates *already running* Workers and their functions; it is complementary, not a',
    'Terraform competitor.',
  ].join(' '),
  '',
  [
    '**API gateways** — Gateways aggregate HTTP at the edge.',
    "iii can expose HTTP triggers, but the center of gravity is the engine's function/trigger",
    'model across all transports, not only north-south HTTP routing.',
  ].join(' '),
  '',
  [
    '**Backend-as-a-service (BaaS)** — BaaS bundles auth, DB, and hosting.',
    'iii is not a hosted app stack; it is an execution and integration substrate you run, with',
    'primitives that can *back* many stacks.',
  ].join(' '),
  '',
  '---',
].join('\n');
