// Writes roadmap/generated/ (gitignored) before `next dev` / `next build`, see
// the package scripts. The roadmap decks used to read two things from Vite:
// the `virtual:spec-manifest` module (the spec list, from the plugin in
// roadmap/scripts/manifest.mjs) and each spec's markdown through
// `import.meta.glob`. Turbopack has neither, so the same data becomes plain
// modules generated from the tech-specs tree:
//
//   generated/spec-manifest.ts      export const SPECS = [...]
//   generated/decks.ts              DECK_SLUGS + loadDeck(slug) (one static
//                                   import() per deck, so each deck is its own chunk)
//   generated/spec-docs/<slug>.ts   SPEC_DOCS: the spec's md keyed by the path the
//                                   old glob produced (../../../../tech-specs/<slug>/<file>)
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { join, resolve } from "node:path"
import { listSpecDocs, ROOT, readSpecs, SPECS_DIR } from "../roadmap/scripts/manifest.mjs"

const OUT = resolve(ROOT, "generated")
const HEADER = "// generated by scripts/generate-roadmap-manifest.ts — do not edit, do not commit\n"

/** What the old `import.meta.glob('../../../../tech-specs/<slug>/*.md')` keyed entries by. */
const globKey = (slug: string, file: string) => `../../../../tech-specs/${slug}/${file}`

export function generateRoadmapManifest(): { specs: number; decks: string[]; warnings: string[] } {
  const { specs, warnings } = readSpecs()

  rmSync(OUT, { recursive: true, force: true })
  mkdirSync(join(OUT, "spec-docs"), { recursive: true })

  // (a) the spec list, typed by the hand-written manifest declarations
  writeFileSync(
    join(OUT, "spec-manifest.ts"),
    `${HEADER}import type { Spec } from "../scripts/manifest.mjs"\n\nexport type SpecEntry = Spec\n\nexport const SPECS: readonly SpecEntry[] = ${JSON.stringify(specs, null, 2)}\n`,
  )

  // (b) the deck registry: every roadmap/<slug>/src/App.tsx, static import() per deck
  const decks = readdirSync(ROOT, { withFileTypes: true })
    .filter((e) => e.isDirectory() && !e.name.startsWith(".") && !e.name.startsWith("_"))
    .map((e) => e.name)
    .filter((name) => existsSync(join(ROOT, name, "src", "App.tsx")))
    .sort()
  const cases = decks
    .map((slug) => `    case ${JSON.stringify(slug)}:\n      return import(${JSON.stringify(`../${slug}/src/App`)})`)
    .join("\n")
  writeFileSync(
    join(OUT, "decks.ts"),
    `${HEADER}import type { ComponentType } from "react"

export const DECK_SLUGS: readonly string[] = ${JSON.stringify(decks, null, 2)}

export function hasDeck(slug: string): boolean {
  return DECK_SLUGS.includes(slug)
}

/** The deck's App component. Each case is a static import so Turbopack emits one chunk per deck. */
export function loadDeck(slug: string): Promise<{ default: ComponentType }> {
  switch (slug) {
${cases}
    default:
      return Promise.reject(new Error(\`no roadmap deck for "\${slug}"\`))
  }
}
`,
  )

  // (c) per deck, the raw spec markdown for the #/spec page
  for (const slug of decks) {
    if (!existsSync(join(SPECS_DIR, slug))) continue // orphan deck: validate-roadmap reports it
    const entries = listSpecDocs(slug).map(({ file }) => {
      const raw = readFileSync(join(SPECS_DIR, slug, file), "utf8")
      return `  ${JSON.stringify(globKey(slug, file))}: ${JSON.stringify(raw)},`
    })
    writeFileSync(
      join(OUT, "spec-docs", `${slug}.ts`),
      `${HEADER}export const SPEC_DOCS: Record<string, string> = {\n${entries.join("\n")}\n}\n`,
    )
  }

  return { specs: specs.length, decks, warnings }
}

const { specs, decks, warnings } = generateRoadmapManifest()
for (const w of warnings) console.warn(`⚠ ${w}`)
console.log(`roadmap manifest: ${specs} spec(s), ${decks.length} deck(s) → roadmap/generated/`)
